name: esendo
description: A new Flutter project.

publish_to: 'none'
version: 36.1.1+37

environment:
  sdk: ">=2.7.0 <3.0.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  built_collection: 5.1.1
  built_value: ^8.3.2
  cached_network_image: ^3.2.1
  cloud_firestore: ^3.1.16
  cloud_firestore_web: ^2.6.15
  firebase_analytics: ^9.1.8
  firebase_auth: ^3.3.18
  firebase_core: ^1.17.0
  firebase_core_web: ^1.6.4
  flutter_datetime_picker: 1.5.1
  flutter_spinkit: ^5.1.0
  font_awesome_flutter: 10.1.0
  google_fonts: ^3.0.1
  google_nav_bar: ^5.0.6
  google_sign_in: ^5.3.2
  intl: 0.17.0
  json_path: ^0.4.0
  json_serializable: ^6.2.0
  page_transition: ^2.0.5
  rxdart: ^0.27.3
  shared_preferences: ^2.0.15
  sign_in_with_apple:
    git:
      url: https://github.com/asmengistu/dart_packages
      ref: ab18d53a80e0a4bb90f1ad84f37f1b408930f28d
      path: packages/sign_in_with_apple/sign_in_with_apple/
  timeago: ^3.2.2
  url_launcher: ^6.1.2
  cupertino_icons: ^1.0.4

dev_dependencies:
  build_runner: ^2.1.11
  built_value_generator: ^8.3.0
  flutter_launcher_icons: 0.9.2

  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/images/app_launcher_icon.png'

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/